configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/browserbase%2Fbrowserbase-af59f86ea3ee682d54560eaf6055df5bebacee560749f5f3cbd9c8ff8b5fa8e5.yml
openapi_spec_hash: 72dfdba2efc46c7cbbaa98bd234b72de
config_hash: 99e5318dc8a8d75839ec565d94276c71
