configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/browserbase%2Fbrowserbase-cd8c38feb61fd4aac23600d0e9e51f11db92b1a119d0e807e61835c05a7bf68e.yml
openapi_spec_hash: 72dfdba2efc46c7cbbaa98bd234b72de
config_hash: 2ac55ea7ba4af84e5b7486df92730bcf
